#!/usr/bin/env zsh

# Adds placeholder so stow doesn't link entire .config or .local folders
[[ -d ~/.config ]] ||
    mkdir -p ~/.config/placeholder
[[ -d ~/.local ]] ||
    mkdir -p ~/.local/placeholder
[[ -d ~/.cargo ]] ||
    mkdir -p ~/.cargo/placeholder

# Set Stow folders
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,cargo,claude,git,macos,config,starship,tmux,zsh"
fi

# Set Dotfiles
if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

# Run install script
STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

