# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "$all$kubernetes$cmd_duration$line_break$jobs$battery$time$status$os$container$shell$character"

# Inserts a blank line between shell prompts
add_newline = false

# Which colour palette to use
palette = "catppuccin_frappe"

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style)'
style = 'bold blue'

[gcloud]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 6

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
