[general]
import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.5
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "Maple Mono", style = "Italic" }
bold_italic = { family = "Maple Mono", style = "Bold Italic" }

# If I want to go back to the days of Comic Sans
# normal = { family = "ComicShannsMono Nerd Font Mono", style = "Regular" }
# bold = { family = "ComicShannsMono Nerd Font Mono", style = "Bold" }
# italic = { family = "ComicShannsMono Nerd Font Mono", style = "Italic" }
# bold_italic = { family = "ComicShannsMono Nerd Font Mono", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[window]
option_as_alt = "Both"

[terminal.shell]
program = "/opt/homebrew/bin/zsh"
