import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[env]
TERM="xterm-256color"

[font]
size=16.0
normal = { family = "ComicShannsMono Nerd Font Mono", style = "Regular" }

[selection]
save_to_clipboard = true

