import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.5
normal = { family = "ComicShannsMono Nerd Font Mono", style = "Regular" }
bold = { family = "ComicShannsMono Nerd Font Mono", style = "Bold" }
italic = { family = "ComicShannsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "ComicShannsMono Nerd Font Mono", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[window]
option_as_alt = "Both"
